version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: symfony_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - symfony
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/symfony?serverVersion=8.0
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    networks:
      - symfony
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - symfony
    depends_on:
      - db

networks:
  symfony:

volumes:
  db_data:
